plugins {
  java
  application
  id("com.diffplug.spotless") version "8.2.1"
}

java { toolchain { languageVersion = JavaLanguageVersion.of(8) } }

application { mainClass.set("org.eclipse.keyple.plugin.pcsc.it.IntegrationTestApp") }

dependencies {
  // Begin Keyple configuration (generated by
  // 'https://keyple.org/components/overview/configuration-wizard/')
  implementation(platform("org.eclipse.keyple:keyple-java-bom:2026.03.19"))
  implementation("org.eclipse.keypop:keypop-reader-java-api")
  implementation("org.eclipse.keyple:keyple-common-java-api")
  implementation("org.eclipse.keyple:keyple-util-java-lib")
  implementation("org.eclipse.keyple:keyple-service-java-lib:4.0.0-SNAPSHOT") { isChanging = true }
  implementation("org.eclipse.keyple:keyple-plugin-pcsc-java-lib")
  // End Keyple configuration

  // Plugin SPI API (exception types: CardIOException, ReaderIOException, …)
  implementation("org.eclipse.keyple:keyple-plugin-java-api:3.0.0-SNAPSHOT") { isChanging = true }

  // SLF4J simple logger for console output
  runtimeOnly("org.slf4j:slf4j-simple:1.7.36")
}

// Produce a runnable fat-jar so the app can be launched without Gradle
tasks.jar {
  manifest { attributes("Main-Class" to "org.eclipse.keyple.plugin.pcsc.it.IntegrationTestApp") }
  duplicatesStrategy = DuplicatesStrategy.WARN
  from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}

tasks {
  spotless {
    java {
      target("src/**/*.java")
      licenseHeaderFile("${project.rootDir}/../LICENSE_HEADER")
      importOrder("java", "javax", "org", "com", "")
      removeUnusedImports()
      googleJavaFormat()
    }
    kotlinGradle {
      target("**/*.kts")
      ktfmt()
    }
  }
}
